package com.escalatorstarter.models

// THIS FILE IS AUTO-GENERATED. REMOVE THIS LINE TO STOP THIS FILE BEING RE-GENERATED
// GENERATED AT: 18-09-25 17:13:10:311

case class EntityId(id: Long) extends AnyVal
case class EntityTag(tag: Option[String]) extends AnyVal

case class Entity(
    id: EntityId,
    keywords: Option[List[String]],
    entityType: EntityType,
    entityObjectId: Option[Long],
    userId: UserId,
    url: Option[String],
    content: Option[String],
    domains: Option[List[String]],
    tag: Option[EntityTag],
    originalImage: Option[String],
    croppedImage: Option[String],
    miniImage: Option[String],
    croppedCoverImage: Option[String],
    blacklisted: Option[Boolean],
    weighting: Option[Double],
    parentEntityId: Option[EntityId],
    wdu: Option[String],
    externalEntityId: Option[String],
    precreated: Option[Boolean],
    verified: Option[Boolean],
    claimed: Option[Boolean],
    claimedAt: Option[escalator.util.Timestamp],
    active: Option[Boolean],
    settings: io.circe.Json,
    personal: io.circe.Json,
    professional: io.circe.Json,
    subline: Option[String],
    countryCode: Option[String],
    hashTags: Option[List[String]],
    searchKeywords: Option[List[String]],
    originalCoverImage: Option[String],
    createdBy: Option[Long],
    validationKeywords: Option[List[String]],
    newsTopics: Option[List[String]],
    newsVerificationRequired: Option[Boolean],
    rejectionKeywords: Option[List[String]],
    refEntityType: Option[EntityType],
    createdAt: escalator.util.Timestamp,
    updatedAt: escalator.util.Timestamp
) extends Persisted

object Entity {

  def apply(
      keywords: Option[List[String]],
      entityType: EntityType,
      entityObjectId: Option[Long],
      userId: UserId,
      url: Option[String],
      content: Option[String],
      domains: Option[List[String]],
      tag: Option[EntityTag],
      originalImage: Option[String],
      croppedImage: Option[String],
      miniImage: Option[String],
      croppedCoverImage: Option[String],
      blacklisted: Option[Boolean],
      weighting: Option[Double],
      parentEntityId: Option[EntityId],
      wdu: Option[String],
      externalEntityId: Option[String],
      precreated: Option[Boolean],
      verified: Option[Boolean],
      claimed: Option[Boolean],
      claimedAt: Option[escalator.util.Timestamp],
      active: Option[Boolean],
      settings: io.circe.Json,
      personal: io.circe.Json,
      professional: io.circe.Json,
      subline: Option[String],
      countryCode: Option[String],
      hashTags: Option[List[String]],
      searchKeywords: Option[List[String]],
      originalCoverImage: Option[String],
      createdBy: Option[Long],
      validationKeywords: Option[List[String]],
      newsTopics: Option[List[String]],
      newsVerificationRequired: Option[Boolean],
      rejectionKeywords: Option[List[String]],
      refEntityType: Option[EntityType]
  ): Entity = {
    Entity(
      EntityId(0L),
      keywords,
      entityType,
      entityObjectId,
      userId,
      url,
      content,
      domains,
      tag,
      originalImage,
      croppedImage,
      miniImage,
      croppedCoverImage,
      blacklisted,
      weighting,
      parentEntityId,
      wdu,
      externalEntityId,
      precreated,
      verified,
      claimed,
      claimedAt,
      active,
      settings,
      personal,
      professional,
      subline,
      countryCode,
      hashTags,
      searchKeywords,
      originalCoverImage,
      createdBy,
      validationKeywords,
      newsTopics,
      newsVerificationRequired,
      rejectionKeywords,
      refEntityType,
      escalator.util.Timestamp(0L),
      escalator.util.Timestamp(0L)
    )
  }

}
